### ISSUE TITLE
Refactor: 빠른시작 도메인을 활동 도메인과 분리하고, 응용 계층 서비스를 도메인 서비스로 이관한다

### ISSUE THREAD

**Issue by anxi01** [KUSITMS-30th-TEAM-C/backend#164]
### 📝 Description

- 빠른시작 도메인을 활동 도메인과 분리합니다.
- 지금 도메인 서비스가 응용계층에 존재하여 이를 도메인 내 서비스로 이관합니다.
---

### 📝 Todo

- [ ] 빠른시작 도메인을 활동 도메인과 분리한다.
- [ ] 응용 계층 서비스를 도메인 서비스로 이관한다.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

This change separates the QuickStart domain from the Activity domain and moves application layer services to the domain layer. It creates new packages for QuickStart, moves relevant files, and adjusts imports accordingly.

You can review changes in this commit: https://github.com/jjyutm4532/KUSITMS-30th-TEAM-C-backend-164/commit/3c089892106d02b7e5812c6103da0bc804c8752e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
